// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lokahiadmin.proto

/*
Package lokahiadmin is a generated protocol buffer package.

lokahiadmin is the administrative/backend API for lokahi power usage.

It is generated from these files:
	lokahiadmin.proto

It has these top-level messages:
	RunRequest
	Check
	ServiceHealth
	Nil
	WebhookRequest
*/
package lokahiadmin

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// RunRequest is a request for a healthcheck being run.
type RunRequest struct {
	Check *Check `protobuf:"bytes,1,opt,name=check" json:"check,omitempty"`
	RunId string `protobuf:"bytes,2,opt,name=run_id,json=runId" json:"run_id,omitempty"`
}

func (m *RunRequest) Reset()                    { *m = RunRequest{} }
func (m *RunRequest) String() string            { return proto.CompactTextString(m) }
func (*RunRequest) ProtoMessage()               {}
func (*RunRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RunRequest) GetCheck() *Check {
	if m != nil {
		return m.Check
	}
	return nil
}

func (m *RunRequest) GetRunId() string {
	if m != nil {
		return m.RunId
	}
	return ""
}

// Check is the database check structure.
// https://github.com/Xe/lokahi/blob/master/internal/database/check.go
type Check struct {
	Id            int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Uuid          string `protobuf:"bytes,2,opt,name=uuid" json:"uuid,omitempty"`
	CreatedAtUnix int64  `protobuf:"varint,3,opt,name=created_at_unix,json=createdAtUnix" json:"created_at_unix,omitempty"`
	EditedAtUnix  int64  `protobuf:"varint,4,opt,name=edited_at_unix,json=editedAtUnix" json:"edited_at_unix,omitempty"`
	Url           string `protobuf:"bytes,5,opt,name=url" json:"url,omitempty"`
	WebhookUrl    string `protobuf:"bytes,6,opt,name=webhook_url,json=webhookUrl" json:"webhook_url,omitempty"`
	Every         int32  `protobuf:"varint,7,opt,name=every" json:"every,omitempty"`
	PlaybookUrl   string `protobuf:"bytes,8,opt,name=playbook_url,json=playbookUrl" json:"playbook_url,omitempty"`
	State         string `protobuf:"bytes,9,opt,name=state" json:"state,omitempty"`
}

func (m *Check) Reset()                    { *m = Check{} }
func (m *Check) String() string            { return proto.CompactTextString(m) }
func (*Check) ProtoMessage()               {}
func (*Check) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Check) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Check) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Check) GetCreatedAtUnix() int64 {
	if m != nil {
		return m.CreatedAtUnix
	}
	return 0
}

func (m *Check) GetEditedAtUnix() int64 {
	if m != nil {
		return m.EditedAtUnix
	}
	return 0
}

func (m *Check) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Check) GetWebhookUrl() string {
	if m != nil {
		return m.WebhookUrl
	}
	return ""
}

func (m *Check) GetEvery() int32 {
	if m != nil {
		return m.Every
	}
	return 0
}

func (m *Check) GetPlaybookUrl() string {
	if m != nil {
		return m.PlaybookUrl
	}
	return ""
}

func (m *Check) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

// ServiceHealth is the health of a relevant service.
type ServiceHealth struct {
	Url                     string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	ResponseTimeNanoseconds int64  `protobuf:"varint,2,opt,name=response_time_nanoseconds,json=responseTimeNanoseconds" json:"response_time_nanoseconds,omitempty"`
	StatusCode              int32  `protobuf:"varint,3,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Error                   string `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
	Healthy                 bool   `protobuf:"varint,5,opt,name=healthy" json:"healthy,omitempty"`
}

func (m *ServiceHealth) Reset()                    { *m = ServiceHealth{} }
func (m *ServiceHealth) String() string            { return proto.CompactTextString(m) }
func (*ServiceHealth) ProtoMessage()               {}
func (*ServiceHealth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ServiceHealth) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ServiceHealth) GetResponseTimeNanoseconds() int64 {
	if m != nil {
		return m.ResponseTimeNanoseconds
	}
	return 0
}

func (m *ServiceHealth) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ServiceHealth) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ServiceHealth) GetHealthy() bool {
	if m != nil {
		return m.Healthy
	}
	return false
}

// Nil is nothing as a type :D
type Nil struct {
}

func (m *Nil) Reset()                    { *m = Nil{} }
func (m *Nil) String() string            { return proto.CompactTextString(m) }
func (*Nil) ProtoMessage()               {}
func (*Nil) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// WebhookRequest contains all of the information needed for webhookworker to
// execute a webhook.
type WebhookRequest struct {
	RunId  string         `protobuf:"bytes,1,opt,name=run_id,json=runId" json:"run_id,omitempty"`
	Check  *Check         `protobuf:"bytes,2,opt,name=check" json:"check,omitempty"`
	Health *ServiceHealth `protobuf:"bytes,3,opt,name=health" json:"health,omitempty"`
}

func (m *WebhookRequest) Reset()                    { *m = WebhookRequest{} }
func (m *WebhookRequest) String() string            { return proto.CompactTextString(m) }
func (*WebhookRequest) ProtoMessage()               {}
func (*WebhookRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *WebhookRequest) GetRunId() string {
	if m != nil {
		return m.RunId
	}
	return ""
}

func (m *WebhookRequest) GetCheck() *Check {
	if m != nil {
		return m.Check
	}
	return nil
}

func (m *WebhookRequest) GetHealth() *ServiceHealth {
	if m != nil {
		return m.Health
	}
	return nil
}

func init() {
	proto.RegisterType((*RunRequest)(nil), "github.xe.lokahi.admin.RunRequest")
	proto.RegisterType((*Check)(nil), "github.xe.lokahi.admin.Check")
	proto.RegisterType((*ServiceHealth)(nil), "github.xe.lokahi.admin.ServiceHealth")
	proto.RegisterType((*Nil)(nil), "github.xe.lokahi.admin.Nil")
	proto.RegisterType((*WebhookRequest)(nil), "github.xe.lokahi.admin.WebhookRequest")
}

func init() { proto.RegisterFile("lokahiadmin.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x55, 0x9a, 0x4d, 0xba, 0x9d, 0x6c, 0x0b, 0x58, 0x7c, 0x84, 0x45, 0x88, 0x12, 0xc1, 0xaa,
	0xa7, 0x1c, 0xba, 0x37, 0x24, 0x0e, 0xb0, 0x42, 0x82, 0x4b, 0x85, 0x0c, 0x2b, 0x60, 0x2f, 0x51,
	0x1a, 0x8f, 0x88, 0xd5, 0xd4, 0x2e, 0x8e, 0xbd, 0xb4, 0xbf, 0x85, 0xff, 0xc0, 0x1f, 0xe4, 0x82,
	0x62, 0x27, 0xa4, 0x2b, 0x51, 0x09, 0x6e, 0x9e, 0x99, 0xf7, 0x3c, 0x6f, 0x9e, 0xc7, 0x70, 0xa7,
	0x92, 0xab, 0xbc, 0xe4, 0x39, 0x5b, 0x73, 0x91, 0x6e, 0x94, 0xd4, 0x92, 0xdc, 0xff, 0xca, 0x75,
	0x69, 0x96, 0xe9, 0x16, 0x53, 0x57, 0x4c, 0x6d, 0x35, 0xf9, 0x0c, 0x40, 0x8d, 0xa0, 0xf8, 0xcd,
	0x60, 0xad, 0xc9, 0x39, 0x04, 0x45, 0x89, 0xc5, 0x2a, 0xf6, 0xa6, 0xde, 0x2c, 0x9a, 0x3f, 0x4e,
	0xff, 0xce, 0x4a, 0x2f, 0x1a, 0x10, 0x75, 0x58, 0x72, 0x0f, 0x42, 0x65, 0x44, 0xc6, 0x59, 0x3c,
	0x98, 0x7a, 0xb3, 0x11, 0x0d, 0x94, 0x11, 0xef, 0x58, 0xf2, 0xcb, 0x83, 0xc0, 0xe2, 0xc8, 0x04,
	0x06, 0x9c, 0xd9, 0x2b, 0x03, 0x3a, 0xe0, 0x8c, 0x10, 0x38, 0x32, 0xe6, 0x0f, 0xdc, 0x9e, 0xc9,
	0x19, 0xdc, 0x2a, 0x14, 0xe6, 0x1a, 0x59, 0x96, 0xeb, 0xcc, 0x08, 0xbe, 0x8d, 0xfd, 0xa9, 0x37,
	0xf3, 0xe9, 0xb8, 0x4d, 0xbf, 0xd2, 0x97, 0x82, 0x6f, 0xc9, 0x33, 0x98, 0x20, 0xe3, 0xfb, 0xb0,
	0x23, 0x0b, 0x3b, 0x71, 0xd9, 0x16, 0x75, 0x1b, 0x7c, 0xa3, 0xaa, 0x38, 0xb0, 0x0d, 0x9a, 0x23,
	0x79, 0x02, 0xd1, 0x77, 0x5c, 0x96, 0x52, 0xae, 0xb2, 0xa6, 0x12, 0xda, 0x0a, 0xb4, 0xa9, 0x4b,
	0x55, 0x91, 0xbb, 0x10, 0xe0, 0x35, 0xaa, 0x5d, 0x3c, 0xb4, 0x3a, 0x5d, 0x40, 0x9e, 0xc2, 0xc9,
	0xa6, 0xca, 0x77, 0xcb, 0x8e, 0x77, 0x6c, 0x79, 0x51, 0x97, 0x6b, 0x89, 0xb5, 0xce, 0x35, 0xc6,
	0x23, 0x37, 0xbd, 0x0d, 0x92, 0x9f, 0x1e, 0x8c, 0x3f, 0xa0, 0xba, 0xe6, 0x05, 0xbe, 0xc5, 0xbc,
	0xd2, 0x65, 0xa7, 0xc9, 0xeb, 0x35, 0xbd, 0x80, 0x87, 0x0a, 0xeb, 0x8d, 0x14, 0x35, 0x66, 0x9a,
	0xaf, 0x31, 0x13, 0xb9, 0x90, 0x35, 0x16, 0x52, 0xb0, 0xda, 0x9a, 0xe3, 0xd3, 0x07, 0x1d, 0xe0,
	0x23, 0x5f, 0xe3, 0xa2, 0x2f, 0x37, 0xf3, 0x34, 0x8d, 0x4c, 0x9d, 0x15, 0x92, 0xa1, 0xf5, 0x2a,
	0xa0, 0xe0, 0x52, 0x17, 0x92, 0xa1, 0x9d, 0x47, 0x29, 0xa9, 0xac, 0x3f, 0x23, 0xea, 0x02, 0x12,
	0xc3, 0xb0, 0xb4, 0x72, 0x76, 0xd6, 0x9c, 0x63, 0xda, 0x85, 0x49, 0x00, 0xfe, 0x82, 0x57, 0xc9,
	0x0f, 0x0f, 0x26, 0x9f, 0x9c, 0x2b, 0xdd, 0x52, 0xf4, 0xef, 0xeb, 0xed, 0xbd, 0x6f, 0xbf, 0x2b,
	0x83, 0xff, 0xd8, 0x95, 0x97, 0x10, 0xba, 0x86, 0x56, 0x71, 0x34, 0x7f, 0x7e, 0x88, 0x75, 0xc3,
	0x3b, 0xda, 0x92, 0xe6, 0x57, 0x10, 0xb6, 0x6e, 0xbe, 0x07, 0x9f, 0x1a, 0x41, 0x92, 0x43, 0xfc,
	0x7e, 0xa9, 0x4f, 0xff, 0xad, 0xc7, 0xfc, 0x0b, 0x0c, 0xdb, 0xc1, 0xc9, 0x02, 0x86, 0x6f, 0xb6,
	0x58, 0x18, 0x8d, 0xe4, 0xec, 0x10, 0xf9, 0xa6, 0x49, 0xa7, 0x8f, 0x0e, 0xe1, 0x16, 0xbc, 0x7a,
	0x3d, 0xbe, 0x8a, 0xf6, 0x7e, 0xe4, 0x32, 0xb4, 0x5f, 0xf2, 0xfc, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x69, 0x9f, 0x86, 0xf8, 0xa7, 0x03, 0x00, 0x00,
}
