// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lokahiadmin.proto

/*
Package lokahiadmin is a generated protocol buffer package.

lokahiadmin is the administrative/backend API for lambda to talk to lokahi.

It is generated from these files:
	lokahiadmin.proto

It has these top-level messages:
*/
package lokahiadmin

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("lokahiadmin.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 71 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0xc9, 0xcf, 0x4e,
	0xcc, 0xc8, 0x4c, 0x4c, 0xc9, 0xcd, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4b,
	0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0xab, 0x48, 0xd5, 0x83, 0x48, 0xea, 0x81, 0x65, 0x9d, 0x78,
	0xa3, 0xb8, 0x91, 0x14, 0x27, 0xb1, 0x81, 0x55, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x41,
	0xa9, 0xee, 0x37, 0x42, 0x00, 0x00, 0x00,
}
