// Code generated by protoc-gen-twirp v5.2.0, DO NOT EDIT.
// source: lokahiadmin.proto

/*
Package lokahiadmin is a generated twirp stub package.
This code was generated with github.com/twitchtv/twirp/protoc-gen-twirp v5.2.0.

lokahiadmin is the administrative/backend API for lokahi power usage.


It is generated from these files:
	lokahiadmin.proto
*/
package lokahiadmin

import bytes "bytes"
import strings "strings"
import context "context"
import fmt "fmt"
import ioutil "io/ioutil"
import log "log"
import http "net/http"

import jsonpb "github.com/golang/protobuf/jsonpb"
import proto "github.com/golang/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Imports only used by utility functions:
import io "io"
import strconv "strconv"
import json "encoding/json"
import url "net/url"

// ==================
// RunLocal Interface
// ==================

type RunLocal interface {
	Checks(context.Context, *CheckIDs) (*Run, error)
}

// ========================
// RunLocal Protobuf Client
// ========================

type runLocalProtobufClient struct {
	client HTTPClient
	urls   [1]string
}

// NewRunLocalProtobufClient creates a Protobuf client that implements the RunLocal interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewRunLocalProtobufClient(addr string, client HTTPClient) RunLocal {
	prefix := urlBase(addr) + RunLocalPathPrefix
	urls := [1]string{
		prefix + "Checks",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &runLocalProtobufClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &runLocalProtobufClient{
		client: client,
		urls:   urls,
	}
}

func (c *runLocalProtobufClient) Checks(ctx context.Context, in *CheckIDs) (*Run, error) {
	ctx = ctxsetters.WithPackageName(ctx, "github.xe.lokahi.admin")
	ctx = ctxsetters.WithServiceName(ctx, "RunLocal")
	ctx = ctxsetters.WithMethodName(ctx, "Checks")
	out := new(Run)
	err := doProtobufRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// ====================
// RunLocal JSON Client
// ====================

type runLocalJSONClient struct {
	client HTTPClient
	urls   [1]string
}

// NewRunLocalJSONClient creates a JSON client that implements the RunLocal interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewRunLocalJSONClient(addr string, client HTTPClient) RunLocal {
	prefix := urlBase(addr) + RunLocalPathPrefix
	urls := [1]string{
		prefix + "Checks",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &runLocalJSONClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &runLocalJSONClient{
		client: client,
		urls:   urls,
	}
}

func (c *runLocalJSONClient) Checks(ctx context.Context, in *CheckIDs) (*Run, error) {
	ctx = ctxsetters.WithPackageName(ctx, "github.xe.lokahi.admin")
	ctx = ctxsetters.WithServiceName(ctx, "RunLocal")
	ctx = ctxsetters.WithMethodName(ctx, "Checks")
	out := new(Run)
	err := doJSONRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// =======================
// RunLocal Server Handler
// =======================

type runLocalServer struct {
	RunLocal
	hooks *twirp.ServerHooks
}

func NewRunLocalServer(svc RunLocal, hooks *twirp.ServerHooks) TwirpServer {
	return &runLocalServer{
		RunLocal: svc,
		hooks:    hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *runLocalServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// RunLocalPathPrefix is used for all URL paths on a twirp RunLocal server.
// Requests are always: POST RunLocalPathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const RunLocalPathPrefix = "/twirp/github.xe.lokahi.admin.RunLocal/"

func (s *runLocalServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "github.xe.lokahi.admin")
	ctx = ctxsetters.WithServiceName(ctx, "RunLocal")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/github.xe.lokahi.admin.RunLocal/Checks":
		s.serveChecks(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *runLocalServer) serveChecks(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveChecksJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveChecksProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *runLocalServer) serveChecksJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Checks")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	defer closebody(req.Body)
	reqContent := new(CheckIDs)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *Run
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.Checks(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *Run and nil error while calling Checks. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)
	if _, err = resp.Write(buf.Bytes()); err != nil {
		log.Printf("errored while writing response to client, but already sent response status code to 200: %s", err)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *runLocalServer) serveChecksProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Checks")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	defer closebody(req.Body)
	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(CheckIDs)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *Run
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.Checks(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *Run and nil error while calling Checks. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if _, err = resp.Write(respBytes); err != nil {
		log.Printf("errored while writing response to client, but already sent response status code to 200: %s", err)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *runLocalServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 0
}

func (s *runLocalServer) ProtocGenTwirpVersion() string {
	return "v5.2.0"
}

// ================
// Health Interface
// ================

// Health is a pseudo-service that runs HTTP health checks.
type Health interface {
	Run(context.Context, *RunRequest) (*ServiceHealth, error)
}

// ======================
// Health Protobuf Client
// ======================

type healthProtobufClient struct {
	client HTTPClient
	urls   [1]string
}

// NewHealthProtobufClient creates a Protobuf client that implements the Health interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewHealthProtobufClient(addr string, client HTTPClient) Health {
	prefix := urlBase(addr) + HealthPathPrefix
	urls := [1]string{
		prefix + "Run",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &healthProtobufClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &healthProtobufClient{
		client: client,
		urls:   urls,
	}
}

func (c *healthProtobufClient) Run(ctx context.Context, in *RunRequest) (*ServiceHealth, error) {
	ctx = ctxsetters.WithPackageName(ctx, "github.xe.lokahi.admin")
	ctx = ctxsetters.WithServiceName(ctx, "Health")
	ctx = ctxsetters.WithMethodName(ctx, "Run")
	out := new(ServiceHealth)
	err := doProtobufRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// ==================
// Health JSON Client
// ==================

type healthJSONClient struct {
	client HTTPClient
	urls   [1]string
}

// NewHealthJSONClient creates a JSON client that implements the Health interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewHealthJSONClient(addr string, client HTTPClient) Health {
	prefix := urlBase(addr) + HealthPathPrefix
	urls := [1]string{
		prefix + "Run",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &healthJSONClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &healthJSONClient{
		client: client,
		urls:   urls,
	}
}

func (c *healthJSONClient) Run(ctx context.Context, in *RunRequest) (*ServiceHealth, error) {
	ctx = ctxsetters.WithPackageName(ctx, "github.xe.lokahi.admin")
	ctx = ctxsetters.WithServiceName(ctx, "Health")
	ctx = ctxsetters.WithMethodName(ctx, "Run")
	out := new(ServiceHealth)
	err := doJSONRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// =====================
// Health Server Handler
// =====================

type healthServer struct {
	Health
	hooks *twirp.ServerHooks
}

func NewHealthServer(svc Health, hooks *twirp.ServerHooks) TwirpServer {
	return &healthServer{
		Health: svc,
		hooks:  hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *healthServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// HealthPathPrefix is used for all URL paths on a twirp Health server.
// Requests are always: POST HealthPathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const HealthPathPrefix = "/twirp/github.xe.lokahi.admin.Health/"

func (s *healthServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "github.xe.lokahi.admin")
	ctx = ctxsetters.WithServiceName(ctx, "Health")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/github.xe.lokahi.admin.Health/Run":
		s.serveRun(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *healthServer) serveRun(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveRunJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveRunProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *healthServer) serveRunJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Run")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	defer closebody(req.Body)
	reqContent := new(RunRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *ServiceHealth
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.Run(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ServiceHealth and nil error while calling Run. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)
	if _, err = resp.Write(buf.Bytes()); err != nil {
		log.Printf("errored while writing response to client, but already sent response status code to 200: %s", err)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *healthServer) serveRunProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Run")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	defer closebody(req.Body)
	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(RunRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *ServiceHealth
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.Run(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ServiceHealth and nil error while calling Run. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if _, err = resp.Write(respBytes); err != nil {
		log.Printf("errored while writing response to client, but already sent response status code to 200: %s", err)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *healthServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 1
}

func (s *healthServer) ProtocGenTwirpVersion() string {
	return "v5.2.0"
}

// =================
// Webhook Interface
// =================

// Webhook executes HTTP webhooks. This is expected to be run asynchronously.
type Webhook interface {
	Execute(context.Context, *WebhookRequest) (*Nil, error)
}

// =======================
// Webhook Protobuf Client
// =======================

type webhookProtobufClient struct {
	client HTTPClient
	urls   [1]string
}

// NewWebhookProtobufClient creates a Protobuf client that implements the Webhook interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewWebhookProtobufClient(addr string, client HTTPClient) Webhook {
	prefix := urlBase(addr) + WebhookPathPrefix
	urls := [1]string{
		prefix + "Execute",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &webhookProtobufClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &webhookProtobufClient{
		client: client,
		urls:   urls,
	}
}

func (c *webhookProtobufClient) Execute(ctx context.Context, in *WebhookRequest) (*Nil, error) {
	ctx = ctxsetters.WithPackageName(ctx, "github.xe.lokahi.admin")
	ctx = ctxsetters.WithServiceName(ctx, "Webhook")
	ctx = ctxsetters.WithMethodName(ctx, "Execute")
	out := new(Nil)
	err := doProtobufRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// ===================
// Webhook JSON Client
// ===================

type webhookJSONClient struct {
	client HTTPClient
	urls   [1]string
}

// NewWebhookJSONClient creates a JSON client that implements the Webhook interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewWebhookJSONClient(addr string, client HTTPClient) Webhook {
	prefix := urlBase(addr) + WebhookPathPrefix
	urls := [1]string{
		prefix + "Execute",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &webhookJSONClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &webhookJSONClient{
		client: client,
		urls:   urls,
	}
}

func (c *webhookJSONClient) Execute(ctx context.Context, in *WebhookRequest) (*Nil, error) {
	ctx = ctxsetters.WithPackageName(ctx, "github.xe.lokahi.admin")
	ctx = ctxsetters.WithServiceName(ctx, "Webhook")
	ctx = ctxsetters.WithMethodName(ctx, "Execute")
	out := new(Nil)
	err := doJSONRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// ======================
// Webhook Server Handler
// ======================

type webhookServer struct {
	Webhook
	hooks *twirp.ServerHooks
}

func NewWebhookServer(svc Webhook, hooks *twirp.ServerHooks) TwirpServer {
	return &webhookServer{
		Webhook: svc,
		hooks:   hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *webhookServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// WebhookPathPrefix is used for all URL paths on a twirp Webhook server.
// Requests are always: POST WebhookPathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const WebhookPathPrefix = "/twirp/github.xe.lokahi.admin.Webhook/"

func (s *webhookServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "github.xe.lokahi.admin")
	ctx = ctxsetters.WithServiceName(ctx, "Webhook")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/github.xe.lokahi.admin.Webhook/Execute":
		s.serveExecute(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *webhookServer) serveExecute(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveExecuteJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveExecuteProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *webhookServer) serveExecuteJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Execute")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	defer closebody(req.Body)
	reqContent := new(WebhookRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *Nil
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.Execute(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *Nil and nil error while calling Execute. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)
	if _, err = resp.Write(buf.Bytes()); err != nil {
		log.Printf("errored while writing response to client, but already sent response status code to 200: %s", err)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *webhookServer) serveExecuteProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Execute")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	defer closebody(req.Body)
	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(WebhookRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *Nil
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.Execute(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *Nil and nil error while calling Execute. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if _, err = resp.Write(respBytes); err != nil {
		log.Printf("errored while writing response to client, but already sent response status code to 200: %s", err)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *webhookServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 2
}

func (s *webhookServer) ProtocGenTwirpVersion() string {
	return "v5.2.0"
}

// =====
// Utils
// =====

// HTTPClient is the interface used by generated clients to send HTTP requests.
// It is fulfilled by *(net/http).Client, which is sufficient for most users.
// Users can provide their own implementation for special retry policies.
//
// HTTPClient implementations should not follow redirects. Redirects are
// automatically disabled if *(net/http).Client is passed to client
// constructors. See the withoutRedirects function in this file for more
// details.
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// TwirpServer is the interface generated server structs will support: they're
// HTTP handlers with additional methods for accessing metadata about the
// service. Those accessors are a low-level API for building reflection tools.
// Most people can think of TwirpServers as just http.Handlers.
type TwirpServer interface {
	http.Handler
	// ServiceDescriptor returns gzipped bytes describing the .proto file that
	// this service was generated from. Once unzipped, the bytes can be
	// unmarshalled as a
	// github.com/golang/protobuf/protoc-gen-go/descriptor.FileDescriptorProto.
	//
	// The returned integer is the index of this particular service within that
	// FileDescriptorProto's 'Service' slice of ServiceDescriptorProtos. This is a
	// low-level field, expected to be used for reflection.
	ServiceDescriptor() ([]byte, int)
	// ProtocGenTwirpVersion is the semantic version string of the version of
	// twirp used to generate this file.
	ProtocGenTwirpVersion() string
}

// WriteError writes an HTTP response with a valid Twirp error format.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func WriteError(resp http.ResponseWriter, err error) {
	writeError(context.Background(), resp, err, nil)
}

// writeError writes Twirp errors in the response and triggers hooks.
func writeError(ctx context.Context, resp http.ResponseWriter, err error, hooks *twirp.ServerHooks) {
	// Non-twirp errors are wrapped as Internal (default)
	twerr, ok := err.(twirp.Error)
	if !ok {
		twerr = twirp.InternalErrorWith(err)
	}

	statusCode := twirp.ServerHTTPStatusFromErrorCode(twerr.Code())
	ctx = ctxsetters.WithStatusCode(ctx, statusCode)
	ctx = callError(ctx, hooks, twerr)

	resp.Header().Set("Content-Type", "application/json") // Error responses are always JSON (instead of protobuf)
	resp.WriteHeader(statusCode)                          // HTTP response status code

	respBody := marshalErrorToJSON(twerr)
	_, err2 := resp.Write(respBody)
	if err2 != nil {
		log.Printf("unable to send error message %q: %s", twerr, err2)
	}

	callResponseSent(ctx, hooks)
}

// urlBase helps ensure that addr specifies a scheme. If it is unparsable
// as a URL, it returns addr unchanged.
func urlBase(addr string) string {
	// If the addr specifies a scheme, use it. If not, default to
	// http. If url.Parse fails on it, return it unchanged.
	url, err := url.Parse(addr)
	if err != nil {
		return addr
	}
	if url.Scheme == "" {
		url.Scheme = "http"
	}
	return url.String()
}

// getCustomHTTPReqHeaders retrieves a copy of any headers that are set in
// a context through the twirp.WithHTTPRequestHeaders function.
// If there are no headers set, or if they have the wrong type, nil is returned.
func getCustomHTTPReqHeaders(ctx context.Context) http.Header {
	header, ok := twirp.HTTPRequestHeaders(ctx)
	if !ok || header == nil {
		return nil
	}
	copied := make(http.Header)
	for k, vv := range header {
		if vv == nil {
			copied[k] = nil
			continue
		}
		copied[k] = make([]string, len(vv))
		copy(copied[k], vv)
	}
	return copied
}

// closebody closes a response or request body and just logs
// any error encountered while closing, since errors are
// considered very unusual.
func closebody(body io.Closer) {
	if err := body.Close(); err != nil {
		log.Printf("error closing body: %q", err)
	}
}

// newRequest makes an http.Request from a client, adding common headers.
func newRequest(ctx context.Context, url string, reqBody io.Reader, contentType string) (*http.Request, error) {
	req, err := http.NewRequest("POST", url, reqBody)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if customHeader := getCustomHTTPReqHeaders(ctx); customHeader != nil {
		req.Header = customHeader
	}
	req.Header.Set("Content-Type", contentType)
	req.Header.Set("Twirp-Version", "v5.2.0")
	return req, nil
}

// JSON serialization for errors
type twerrJSON struct {
	Code string            `json:"code"`
	Msg  string            `json:"msg"`
	Meta map[string]string `json:"meta,omitempty"`
}

// marshalErrorToJSON returns JSON from a twirp.Error, that can be used as HTTP error response body.
// If serialization fails, it will use a descriptive Internal error instead.
func marshalErrorToJSON(twerr twirp.Error) []byte {
	// make sure that msg is not too large
	msg := twerr.Msg()
	if len(msg) > 1e6 {
		msg = msg[:1e6]
	}

	tj := twerrJSON{
		Code: string(twerr.Code()),
		Msg:  msg,
		Meta: twerr.MetaMap(),
	}

	buf, err := json.Marshal(&tj)
	if err != nil {
		buf = []byte("{\"type\": \"" + twirp.Internal + "\", \"msg\": \"There was an error but it could not be serialized into JSON\"}") // fallback
	}

	return buf
}

// errorFromResponse builds a twirp.Error from a non-200 HTTP response.
// If the response has a valid serialized Twirp error, then it's returned.
// If not, the response status code is used to generate a similar twirp
// error. See twirpErrorFromIntermediary for more info on intermediary errors.
func errorFromResponse(resp *http.Response) twirp.Error {
	statusCode := resp.StatusCode
	statusText := http.StatusText(statusCode)

	if isHTTPRedirect(statusCode) {
		// Unexpected redirect: it must be an error from an intermediary.
		// Twirp clients don't follow redirects automatically, Twirp only handles
		// POST requests, redirects should only happen on GET and HEAD requests.
		location := resp.Header.Get("Location")
		msg := fmt.Sprintf("unexpected HTTP status code %d %q received, Location=%q", statusCode, statusText, location)
		return twirpErrorFromIntermediary(statusCode, msg, location)
	}

	respBodyBytes, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return clientError("failed to read server error response body", err)
	}
	var tj twerrJSON
	if err := json.Unmarshal(respBodyBytes, &tj); err != nil {
		// Invalid JSON response; it must be an error from an intermediary.
		msg := fmt.Sprintf("Error from intermediary with HTTP status code %d %q", statusCode, statusText)
		return twirpErrorFromIntermediary(statusCode, msg, string(respBodyBytes))
	}

	errorCode := twirp.ErrorCode(tj.Code)
	if !twirp.IsValidErrorCode(errorCode) {
		msg := "invalid type returned from server error response: " + tj.Code
		return twirp.InternalError(msg)
	}

	twerr := twirp.NewError(errorCode, tj.Msg)
	for k, v := range tj.Meta {
		twerr = twerr.WithMeta(k, v)
	}
	return twerr
}

// twirpErrorFromIntermediary maps HTTP errors from non-twirp sources to twirp errors.
// The mapping is similar to gRPC: https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md.
// Returned twirp Errors have some additional metadata for inspection.
func twirpErrorFromIntermediary(status int, msg string, bodyOrLocation string) twirp.Error {
	var code twirp.ErrorCode
	if isHTTPRedirect(status) { // 3xx
		code = twirp.Internal
	} else {
		switch status {
		case 400: // Bad Request
			code = twirp.Internal
		case 401: // Unauthorized
			code = twirp.Unauthenticated
		case 403: // Forbidden
			code = twirp.PermissionDenied
		case 404: // Not Found
			code = twirp.BadRoute
		case 429, 502, 503, 504: // Too Many Requests, Bad Gateway, Service Unavailable, Gateway Timeout
			code = twirp.Unavailable
		default: // All other codes
			code = twirp.Unknown
		}
	}

	twerr := twirp.NewError(code, msg)
	twerr = twerr.WithMeta("http_error_from_intermediary", "true") // to easily know if this error was from intermediary
	twerr = twerr.WithMeta("status_code", strconv.Itoa(status))
	if isHTTPRedirect(status) {
		twerr = twerr.WithMeta("location", bodyOrLocation)
	} else {
		twerr = twerr.WithMeta("body", bodyOrLocation)
	}
	return twerr
}
func isHTTPRedirect(status int) bool {
	return status >= 300 && status <= 399
}

// wrappedError implements the github.com/pkg/errors.Causer interface, allowing errors to be
// examined for their root cause.
type wrappedError struct {
	msg   string
	cause error
}

func wrapErr(err error, msg string) error { return &wrappedError{msg: msg, cause: err} }
func (e *wrappedError) Cause() error      { return e.cause }
func (e *wrappedError) Error() string     { return e.msg + ": " + e.cause.Error() }

// clientError adds consistency to errors generated in the client
func clientError(desc string, err error) twirp.Error {
	return twirp.InternalErrorWith(wrapErr(err, desc))
}

// badRouteError is used when the twirp server cannot route a request
func badRouteError(msg string, method, url string) twirp.Error {
	err := twirp.NewError(twirp.BadRoute, msg)
	err = err.WithMeta("twirp_invalid_route", method+" "+url)
	return err
}

// The standard library will, by default, redirect requests (including POSTs) if it gets a 302 or
// 303 response, and also 301s in go1.8. It redirects by making a second request, changing the
// method to GET and removing the body. This produces very confusing error messages, so instead we
// set a redirect policy that always errors. This stops Go from executing the redirect.
//
// We have to be a little careful in case the user-provided http.Client has its own CheckRedirect
// policy - if so, we'll run through that policy first.
//
// Because this requires modifying the http.Client, we make a new copy of the client and return it.
func withoutRedirects(in *http.Client) *http.Client {
	copy := *in
	copy.CheckRedirect = func(req *http.Request, via []*http.Request) error {
		if in.CheckRedirect != nil {
			// Run the input's redirect if it exists, in case it has side effects, but ignore any error it
			// returns, since we want to use ErrUseLastResponse.
			err := in.CheckRedirect(req, via)
			_ = err // Silly, but this makes sure generated code passes errcheck -blank, which some people use.
		}
		return http.ErrUseLastResponse
	}
	return &copy
}

// doProtobufRequest is common code to make a request to the remote twirp service.
func doProtobufRequest(ctx context.Context, client HTTPClient, url string, in, out proto.Message) (err error) {
	reqBodyBytes, err := proto.Marshal(in)
	if err != nil {
		return clientError("failed to marshal proto request", err)
	}
	reqBody := bytes.NewBuffer(reqBodyBytes)
	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	req, err := newRequest(ctx, url, reqBody, "application/protobuf")
	if err != nil {
		return clientError("could not build request", err)
	}
	resp, err := client.Do(req)
	if err != nil {
		return clientError("failed to do request", err)
	}

	defer func() {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = clientError("failed to close response body", cerr)
		}
	}()

	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	if resp.StatusCode != 200 {
		return errorFromResponse(resp)
	}

	respBodyBytes, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return clientError("failed to read response body", err)
	}
	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	if err = proto.Unmarshal(respBodyBytes, out); err != nil {
		return clientError("failed to unmarshal proto response", err)
	}
	return nil
}

// doJSONRequest is common code to make a request to the remote twirp service.
func doJSONRequest(ctx context.Context, client HTTPClient, url string, in, out proto.Message) (err error) {
	reqBody := bytes.NewBuffer(nil)
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(reqBody, in); err != nil {
		return clientError("failed to marshal json request", err)
	}
	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	req, err := newRequest(ctx, url, reqBody, "application/json")
	if err != nil {
		return clientError("could not build request", err)
	}
	resp, err := client.Do(req)
	if err != nil {
		return clientError("failed to do request", err)
	}

	defer func() {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = clientError("failed to close response body", cerr)
		}
	}()

	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	if resp.StatusCode != 200 {
		return errorFromResponse(resp)
	}

	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(resp.Body, out); err != nil {
		return clientError("failed to unmarshal json response", err)
	}
	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}
	return nil
}

// Call twirp.ServerHooks.RequestReceived if the hook is available
func callRequestReceived(ctx context.Context, h *twirp.ServerHooks) (context.Context, error) {
	if h == nil || h.RequestReceived == nil {
		return ctx, nil
	}
	return h.RequestReceived(ctx)
}

// Call twirp.ServerHooks.RequestRouted if the hook is available
func callRequestRouted(ctx context.Context, h *twirp.ServerHooks) (context.Context, error) {
	if h == nil || h.RequestRouted == nil {
		return ctx, nil
	}
	return h.RequestRouted(ctx)
}

// Call twirp.ServerHooks.ResponsePrepared if the hook is available
func callResponsePrepared(ctx context.Context, h *twirp.ServerHooks) context.Context {
	if h == nil || h.ResponsePrepared == nil {
		return ctx
	}
	return h.ResponsePrepared(ctx)
}

// Call twirp.ServerHooks.ResponseSent if the hook is available
func callResponseSent(ctx context.Context, h *twirp.ServerHooks) {
	if h == nil || h.ResponseSent == nil {
		return
	}
	h.ResponseSent(ctx)
}

// Call twirp.ServerHooks.Error if the hook is available
func callError(ctx context.Context, h *twirp.ServerHooks, err twirp.Error) context.Context {
	if h == nil || h.Error == nil {
		return ctx
	}
	return h.Error(ctx, err)
}

var twirpFileDescriptor0 = []byte{
	// 668 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0x96, 0xe3, 0xd8, 0x49, 0x26, 0x6d, 0xcf, 0x39, 0x7b, 0xce, 0x01, 0x13, 0x40, 0x0d, 0x16,
	0x54, 0xb9, 0x0a, 0x52, 0xca, 0x05, 0x2a, 0xe2, 0x82, 0xfe, 0x08, 0x2a, 0xa1, 0x08, 0x6d, 0xa9,
	0x80, 0xde, 0x44, 0x8e, 0x77, 0x20, 0xab, 0xb8, 0xeb, 0xb0, 0x3f, 0x25, 0x79, 0x16, 0xde, 0x86,
	0x97, 0xe1, 0x21, 0xb8, 0x41, 0xde, 0xb5, 0x9b, 0x54, 0x22, 0xa5, 0xdc, 0xed, 0xcc, 0x7c, 0x33,
	0x3b, 0xf3, 0xed, 0x37, 0x0b, 0xff, 0x64, 0xf9, 0x34, 0x99, 0xf0, 0x84, 0x9d, 0x73, 0xd1, 0x9f,
	0xc9, 0x5c, 0xe7, 0xe4, 0xd6, 0x27, 0xae, 0x27, 0x66, 0xdc, 0x9f, 0x63, 0xdf, 0x05, 0xfb, 0x36,
	0x1a, 0xdf, 0x83, 0xe6, 0xc1, 0x04, 0xd3, 0xe9, 0xf1, 0xa1, 0x22, 0x7f, 0x83, 0xcf, 0x99, 0x8a,
	0xbc, 0xae, 0xdf, 0x6b, 0xd1, 0xe2, 0x18, 0xbf, 0x07, 0xa0, 0x46, 0x50, 0xfc, 0x6c, 0x50, 0x69,
	0xb2, 0x0b, 0x41, 0x5a, 0x60, 0x23, 0xaf, 0xeb, 0xf5, 0xda, 0x83, 0xfb, 0xfd, 0x5f, 0xd7, 0xec,
	0xdb, 0x82, 0xd4, 0x61, 0xc9, 0xff, 0x10, 0x4a, 0x23, 0x46, 0x9c, 0x45, 0xb5, 0xae, 0xd7, 0x6b,
	0xd1, 0x40, 0x1a, 0x71, 0xcc, 0xe2, 0x6f, 0x1e, 0x6c, 0x9e, 0xa0, 0xbc, 0xe0, 0x29, 0xbe, 0xc2,
	0x24, 0xd3, 0x93, 0xe2, 0x76, 0x23, 0x33, 0x5b, 0xbb, 0x45, 0x8b, 0x23, 0xd9, 0x83, 0x3b, 0x12,
	0xd5, 0x2c, 0x17, 0x0a, 0x47, 0x9a, 0x9f, 0xe3, 0x48, 0x24, 0x22, 0x57, 0x98, 0xe6, 0x82, 0x29,
	0x5b, 0xcd, 0xa7, 0xb7, 0x2b, 0xc0, 0x5b, 0x7e, 0x8e, 0xc3, 0x65, 0x98, 0x6c, 0x43, 0x5b, 0xe9,
	0x44, 0x1b, 0x35, 0x4a, 0x73, 0x86, 0x91, 0xdf, 0xf5, 0x7a, 0x01, 0x05, 0xe7, 0x3a, 0xc8, 0x19,
	0x12, 0x02, 0xf5, 0x71, 0xce, 0x16, 0x51, 0xdd, 0xde, 0x67, 0xcf, 0xe4, 0x3f, 0x08, 0x50, 0xca,
	0x5c, 0x46, 0x81, 0x6b, 0xd5, 0x1a, 0x24, 0x82, 0xc6, 0xc4, 0xb6, 0xb8, 0x88, 0xc2, 0xae, 0xd7,
	0x6b, 0xd2, 0xca, 0x8c, 0xbf, 0xd7, 0xc0, 0xa7, 0x46, 0x90, 0x2d, 0xa8, 0x71, 0x56, 0x76, 0x5e,
	0xe3, 0x8c, 0x3c, 0x81, 0x7a, 0xca, 0xcb, 0x1e, 0xdb, 0x83, 0xee, 0xb5, 0x3c, 0x1d, 0x1f, 0x2a,
	0x6a, 0xd1, 0xa4, 0x03, 0xcd, 0x8f, 0x5c, 0x70, 0x35, 0x41, 0x66, 0xfb, 0x6d, 0xd2, 0x4b, 0x9b,
	0xec, 0x43, 0x43, 0xa2, 0x32, 0x99, 0x56, 0x51, 0xbd, 0xeb, 0xf7, 0xda, 0x83, 0xde, 0xba, 0xa2,
	0xd4, 0x88, 0x3e, 0x75, 0xd0, 0x23, 0xa1, 0xe5, 0x82, 0x56, 0x89, 0x64, 0x07, 0xfe, 0x52, 0x3a,
	0x91, 0xda, 0x71, 0x69, 0x04, 0x9f, 0xdb, 0x39, 0x7d, 0xba, 0x69, 0xdd, 0x05, 0x83, 0xa7, 0x82,
	0xcf, 0xc9, 0x63, 0xf8, 0x17, 0xb3, 0x64, 0xa6, 0x90, 0x5d, 0x21, 0x3c, 0xb4, 0x58, 0x52, 0x86,
	0x56, 0xb8, 0xee, 0x24, 0xb0, 0xb1, 0x7a, 0x63, 0xf1, 0x92, 0x53, 0x5c, 0x54, 0x2f, 0x39, 0xc5,
	0x05, 0x79, 0x06, 0xc1, 0x45, 0x92, 0x19, 0x2c, 0x19, 0x79, 0xb4, 0xae, 0xf9, 0x2b, 0x8a, 0xa0,
	0x2e, 0x67, 0xaf, 0xf6, 0xd4, 0x8b, 0x03, 0xf0, 0x87, 0x3c, 0x8b, 0x7f, 0x78, 0x10, 0x58, 0xd6,
	0x56, 0x28, 0x0f, 0x2c, 0xe5, 0x04, 0xea, 0xc6, 0x5c, 0x8a, 0xcc, 0x9e, 0x8b, 0x81, 0x53, 0x89,
	0x89, 0x46, 0x36, 0x4a, 0xb4, 0x1b, 0xd8, 0x77, 0x03, 0x97, 0xee, 0x17, 0xda, 0x0e, 0xfc, 0x10,
	0xb6, 0x90, 0xf1, 0x55, 0x58, 0xdd, 0xc2, 0x36, 0x9c, 0xb7, 0x44, 0x95, 0xfa, 0x0c, 0x96, 0xfa,
	0xdc, 0x86, 0xf6, 0x17, 0x1c, 0x4f, 0xf2, 0x7c, 0x3a, 0x2a, 0x22, 0xa1, 0x8d, 0x40, 0xe9, 0x3a,
	0x95, 0x99, 0xd5, 0xd3, 0x05, 0xca, 0x45, 0xd4, 0xb0, 0x7d, 0x3a, 0x83, 0x3c, 0x80, 0x8d, 0x59,
	0x96, 0x2c, 0xc6, 0x55, 0x5e, 0xd3, 0xe6, 0xb5, 0x2b, 0x5f, 0x99, 0x58, 0x48, 0x15, 0xa3, 0x96,
	0x13, 0xa2, 0x35, 0xe2, 0xaf, 0x1e, 0x6c, 0xbd, 0x73, 0xd5, 0xab, 0x95, 0x5c, 0x6e, 0x97, 0xb7,
	0xb2, 0x5d, 0xcb, 0x4d, 0xad, 0xfd, 0xc1, 0xa6, 0x3e, 0x87, 0xd0, 0x09, 0xdb, 0xb2, 0x74, 0xe3,
	0x57, 0x2a, 0x93, 0x06, 0x27, 0xd0, 0xa4, 0x46, 0xbc, 0xce, 0xd3, 0x24, 0x23, 0x2f, 0x21, 0xb4,
	0xa5, 0x15, 0xf9, 0xad, 0xf8, 0x3b, 0x77, 0xaf, 0x51, 0xf2, 0xe0, 0x0c, 0xc2, 0xf2, 0x7b, 0x78,
	0xe3, 0x56, 0x2d, 0xbe, 0x06, 0x5d, 0x92, 0xd2, 0xb9, 0x59, 0xe3, 0x83, 0x0f, 0xd0, 0x28, 0xd9,
	0x24, 0x43, 0x68, 0x1c, 0xcd, 0x31, 0x35, 0x1a, 0xc9, 0xce, 0xba, 0xe4, 0xab, 0xcc, 0xaf, 0x6f,
	0x7b, 0xc8, 0xb3, 0xfd, 0xcd, 0xb3, 0xf6, 0xca, 0x17, 0x3c, 0x0e, 0xed, 0x1f, 0xbc, 0xfb, 0x33,
	0x00, 0x00, 0xff, 0xff, 0xdb, 0x7a, 0xbf, 0x85, 0x98, 0x05, 0x00, 0x00,
}
