language: go

install: 
  - go get github.com/twitchtv/retool
  - curl -L https://github.com/google/protobuf/releases/download/v3.0.0-beta-2/protoc-3.0.0-beta-2-linux-x86_64.zip > protoc-release.zip
  - mkdir -p ~/.local/bin
  - unzip -p protoc-release.zip protoc > $HOME/.local/bin/protoc
  - chmod a+x $HOME/.local/bin/protoc
  - rm protoc-release.zip

go:
  - 1.x

script:
  - retool do mage -v travis
